const blockedDomains = [
    'doubleclick.net',
    'ads.pubmatic.com',
    'taboola.com',
    'adservice.google.com',
    'ad.doubleclick.net',
    'googlesyndication.com',
    'amazon-adsystem.com',
    'connect.facebook.net',
    'outbrain.com',
    'criteo.com',
    'scorecardresearch.com',
    'adnxs.com',
    'yimg.com',
    'advertising.com',
    'zedo.com',
    'smartadserver.com',
    'adsafeprotected.com',
    'moatads.com',
    'yieldmanager.com',
    'revcontent.com',
    '*://*.youtube.com/get_video_info*',
    '*://*.youtube.com/watch*',
    '*://*.googleads.g.doubleclick.net/*',
    'media.net',
    'gumgum.com',
    'mediafire.com',
    'popads.net',
    'adroll.com',
    'adserver.com',
    'adtech.com',
    'servedbyadserver.com',
    'ads.yahoo.com',
    'adfly.com',
    'admarketplace.com',
    'adperceptions.com',
    'mopub.com',
    'clicksor.com',
    'adnetwork.com',
    'advertisingnetwork.com',
    'vungle.com',
    'yahoo.com',
    'tremorhub.com',
    'adbutler.com',
    'popcash.net',
    'admaster.com',
    'juicyads.com',
    'popunder.com',
    'adf.ly',
    // Add more domains as needed...
];

chrome.runtime.onInstalled.addListener(() => {
    const rules = blockedDomains.map((domain, index) => ({
        id: index + 1,
        priority: 1,
        action: { type: 'block' },
        condition: { urlFilter: domain, resourceTypes: ['script', 'image', 'xmlhttprequest'] },
    }));

    chrome.declarativeNetRequest.updateDynamicRules({
        addRules: rules,
        removeRuleIds: rules.map((rule) => rule.id),
    });
});
